/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peliculas;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lab02-17
 */
public class main extends javax.swing.JFrame {

    private UIManager.LookAndFeelInfo apariencias[];
    private Peliculas peliculas;
    private DefaultTableModel modelo = new DefaultTableModel();
    
    public main() {
        initComponents();
        apariencias = UIManager.getInstalledLookAndFeels();
        try{
            UIManager.setLookAndFeel(apariencias[1].getClassName());
            SwingUtilities.updateComponentTreeUI(this);
            peliculas = new Peliculas();
            tabla.setModel(modelo);
            modelo.addColumn("Id");
            modelo.addColumn("Nombre");
            modelo.addColumn("Genero");
            modelo.addColumn("Año");
            modelo.addColumn("Actor");
            modelo.addColumn("País");
            this.cargaPeliculas();
        }catch(Exception e){
        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtactor = new javax.swing.JTextField();
        cbgenero = new javax.swing.JComboBox();
        cbpais = new javax.swing.JComboBox();
        btnregistrar = new javax.swing.JButton();
        cbanio = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        cbgenero1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbanio1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbpais1 = new javax.swing.JComboBox();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbpeliculas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtactor1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbpeliculas1 = new javax.swing.JComboBox();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 490));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(250, 150));
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(668, 486));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setText("Lista de peliculas");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel1);

        jLabel5.setText("Nombre: ");

        jLabel6.setText("Género:");

        jLabel7.setText("Año:");

        jLabel8.setText("Actor:");

        jLabel9.setText("País:");

        cbgenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Accion", "Ciencia Ficción", "Comedia", "Drama", "Thriller", "Romantica", "Suspenso", "Terror", " " }));

        cbpais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Argentina", "Bolivia", "Brazil", "Canada", "Colombia", "Chile", "Cuba", "Ecuador", "España", "Estados Unidos", "Guatemala", "Jamaica", "Paraguay", "Peru", "Uruguay", "Venezuela", " " }));

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        cbanio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtactor)
                            .addComponent(cbpais, 0, 150, Short.MAX_VALUE)
                            .addComponent(cbgenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnombre)
                            .addComponent(cbanio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbanio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtactor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cbpais, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registra Película", jPanel2);

        jLabel10.setText("Nombre: ");

        jLabel11.setText("Género:");

        cbgenero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Accion", "Ciencia Ficción", "Comedia", "Drama", "Thriller", "Romantica", "Suspenso", "Terror", " " }));

        jLabel12.setText("Año:");

        cbanio1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        jLabel13.setText("Actor:");

        jLabel14.setText("País:");

        cbpais1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Argentina", "Bolivia", "Brazil", "Canada", "Colombia", "Chile", "Cuba", "Ecuador", "España", "Estados Unidos", "Guatemala", "Jamaica", "Paraguay", "Peru", "Uruguay", "Venezuela", " " }));

        btnActualizar.setText("Modificar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar(evt);
            }
        });

        jLabel2.setText("BUSCAR PELICULA");

        cbpeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcargapeliculas(evt);
            }
        });

        jLabel3.setText("Id");

        txtid.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(cbpeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel14)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbpais1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbgenero1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnombre1)
                                .addComponent(cbanio1, 0, 150, Short.MAX_VALUE)
                                .addComponent(txtid)
                                .addComponent(txtactor1)))))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbpeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cbgenero1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbanio1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtactor1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cbpais1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("Actualizar Película", jPanel3);

        jLabel4.setText("Buscar pelicula");

        btnEliminar.setText("Eliminar Pelicula");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(cbpeliculas1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbpeliculas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Película", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        String nombre = txtnombre.getText();
        String actor = txtactor.getText();
        //
        if(nombre.trim().length()==0 || actor.trim().length()==0){
            JOptionPane.showMessageDialog(this, "Falta LLenar Algunos Datos", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int anio = Integer.parseInt(cbanio.getSelectedItem().toString());
        String genero =cbgenero.getSelectedItem().toString();
        String pais = cbpais.getSelectedItem().toString();
        if(peliculas.insert(nombre,genero,anio,actor,pais) ){
        JOptionPane.showMessageDialog(this, "Pelicula registrada con éxito", "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
                txtnombre.setText("");
                txtactor.setText("");
                //falta jpntionp
                cargaPeliculas();
        }else{
        JOptionPane.showMessageDialog(this, "Error al registrar la película", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void Actualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar
       int id;
        try {
            id = Integer.parseInt(txtid.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ninguna Pelicula Seleccionada.", "Extio", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String nombre = txtnombre1.getText();
        String actor = txtactor1.getText();
        //Si algun jtextfield no esta lleno mandamos un error
        if(nombre.trim().length()==0 || actor.trim().length()==0){
            JOptionPane.showMessageDialog(this, "Falta LLenar Algunos Datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int anio = Integer.parseInt(cbanio1.getSelectedItem().toString());
        String genero = cbgenero1.getSelectedItem().toString();
        String pais = cbpais1.getSelectedItem().toString();
        
        if(peliculas.update(id,nombre, genero, anio, actor, pais)){
            JOptionPane.showMessageDialog(this, "Pelicula registrada con exito.", "Extio", JOptionPane.INFORMATION_MESSAGE);
            txtactor1.setText("");
            txtnombre1.setText("");
            cbpeliculas.removeAllItems();
            cbpeliculas1.removeAllItems();
            cargaPeliculas();
        }else{
            JOptionPane.showMessageDialog(this, "Error al registrar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_Actualizar

    private void cbcargapeliculas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcargapeliculas
        Pelicula pel = (Pelicula)cbpeliculas.getSelectedItem();
        if(pel == null) return;
        txtid.setText(pel.getId()+"");
        txtnombre1.setText(pel.getNombre());
        for (int i = 0; i <cbgenero1.getItemCount();i++){
            if(pel.getGenero().equals(cbgenero1.getItemAt(i).toString()) ){
            cbgenero1.setSelectedIndex(i);
            break;
            }
        }
        cbanio1.addItem(pel.getAnio());
        cbanio1.setSelectedIndex(cbanio1.getItemCount()-1);
        txtactor1.setText(pel.getActor());
        for (int i = 0; i <cbpais1.getItemCount();i++){
            if(pel.getPais().equals(cbpais1.getItemAt(i).toString()) ){
            cbpais1.setSelectedIndex(i);
            break;
            }
        } 
        
    }//GEN-LAST:event_cbcargapeliculas

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         Pelicula pel = (Pelicula) cbpeliculas1.getSelectedItem();
        if(pel == null)return;
            if(peliculas.delete(pel.getId())){
                JOptionPane.showMessageDialog(this, "La pelicula se elimino con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
                cbpeliculas.removeAllItems();
                cbpeliculas1.removeAllItems();
                cargaPeliculas();
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la pelicula", "Error", JOptionPane.ERROR_MESSAGE);
            }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void BuscarGenero(){
        if(cbgenero.getSelectedIndex()==0 ){
        cargaPeliculas();
        return;
        }
        limpiartabla();
        try{
        ResultSet rs = peliculas.SelectXgenero
        (cbgenero.getSelectedItem().toString());
            while(rs.next() ){
            Object row[] = new Object[6];
                for(int i=0; i<6; i++ ){
                row[i] = rs.getObject(i+1);}
                //agregar cada registro al modelo de la tabla
                 modelo.addRow(row);
            }
        }
        catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "error al cargar los datos",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    //cargar peliculas..
    private void cargaPeliculas(){
     limpiartabla();
        try{ 
            ResultSet rs = peliculas.SelectXtodas();
            while(rs.next() ){
            Object row[] = new Object[6];
                for(int i=0; i<6; i++ ){
                row[i] = rs.getObject(i+1);}
                //agregar cada registro al modelo de la tabla
                 modelo.addRow(row);
                //cargar jcombox
                cbpeliculas.addItem(new Pelicula(Integer.parseInt(row[0].toString()),row[1].toString(),row[2].toString(),
                        Integer.parseInt(row[3].toString()),row[4].toString(),row[5].toString()));
                cbpeliculas1.addItem(new Pelicula(Integer.parseInt(row[0].toString()),row[1].toString(),row[2].toString(),
                        Integer.parseInt(row[3].toString()),row[4].toString(),row[5].toString()));
                 
            }           
        }catch (Exception e ) {
        JOptionPane.showMessageDialog(this, "Error al cargar los tados de la DB."
                , "error", JOptionPane.ERROR_MESSAGE);

        }    
    }

    private void limpiartabla() {
        for(int i=0; i< modelo.getRowCount() ; i++){
              modelo.removeRow(i);
              i-=1;
        }
   }
    
    class Pelicula{    
    private int id, anio;
    private String nombre, pais, genero, actor;
        
        public Pelicula(int id, String nombre, String genero, 
                int anio, String actor, String pais ) {
            this.id = id;
            this.nombre = nombre;
            this.genero = genero;
            this.anio = anio;
            this.pais = pais;
            this.actor = actor;            
        } //gets
        public int getId(){return id;}
        public String getNombre(){return nombre;};
        public String getGenero(){return genero;};
        public int getAnio(){return anio;};
        public String getPais(){return pais;};
        public String getActor(){return actor;};
          //sets
        public void setGenero(String genero){this.genero = genero;}
        public void setAnio(int anio){this.anio = anio;}
        public void setPais(String pais){this.pais = pais;}
        public void setActor(String actor){this.pais = actor;}
        @Override        
        public String toString(){return nombre;}
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox cbanio;
    private javax.swing.JComboBox cbanio1;
    private javax.swing.JComboBox cbgenero;
    private javax.swing.JComboBox cbgenero1;
    private javax.swing.JComboBox cbpais;
    private javax.swing.JComboBox cbpais1;
    private javax.swing.JComboBox cbpeliculas;
    private javax.swing.JComboBox cbpeliculas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtactor;
    private javax.swing.JTextField txtactor1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    // End of variables declaration//GEN-END:variables
}
